name: tvent
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  crystal_navigation_bar: ^1.0.0
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  font_awesome_flutter: ^10.6.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

assets:
  - assets/images/
